import type { PlatformRow } from './rows.js';
import type { CollectionStore } from './types.js';

/**
 * Seed data for the 25 built-in gaming platforms.
 * rom_extensions are native string[] (no JSON stringification needed).
 */
const SEED_PLATFORMS: Omit<PlatformRow, 'created_at' | 'updated_at'>[] = [
  // Nintendo
  {
    id: 'nes',
    name: 'Nintendo Entertainment System',
    short_name: 'NES',
    manufacturer: 'Nintendo',
    generation: 3,
    release_year: 1983,
    icon_path: null,
    wallpaper_path: null,
    color: '#E60012',
    rom_extensions: ['.nes', '.unf', '.unif'],
  },
  {
    id: 'snes',
    name: 'Super Nintendo Entertainment System',
    short_name: 'SNES',
    manufacturer: 'Nintendo',
    generation: 4,
    release_year: 1990,
    icon_path: null,
    wallpaper_path: null,
    color: '#7B68EE',
    rom_extensions: ['.sfc', '.smc', '.fig', '.swc'],
  },
  {
    id: 'n64',
    name: 'Nintendo 64',
    short_name: 'N64',
    manufacturer: 'Nintendo',
    generation: 5,
    release_year: 1996,
    icon_path: null,
    wallpaper_path: null,
    color: '#008000',
    rom_extensions: ['.n64', '.v64', '.z64'],
  },
  {
    id: 'gc',
    name: 'Nintendo GameCube',
    short_name: 'GC',
    manufacturer: 'Nintendo',
    generation: 6,
    release_year: 2001,
    icon_path: null,
    wallpaper_path: null,
    color: '#663399',
    rom_extensions: ['.iso', '.gcm', '.gcz', '.rvz'],
  },
  {
    id: 'wii',
    name: 'Nintendo Wii',
    short_name: 'Wii',
    manufacturer: 'Nintendo',
    generation: 7,
    release_year: 2006,
    icon_path: null,
    wallpaper_path: null,
    color: '#00BFFF',
    rom_extensions: ['.iso', '.wbfs', '.rvz', '.wia'],
  },
  {
    id: 'gb',
    name: 'Game Boy',
    short_name: 'GB',
    manufacturer: 'Nintendo',
    generation: 4,
    release_year: 1989,
    icon_path: null,
    wallpaper_path: null,
    color: '#8B8B00',
    rom_extensions: ['.gb'],
  },
  {
    id: 'gbc',
    name: 'Game Boy Color',
    short_name: 'GBC',
    manufacturer: 'Nintendo',
    generation: 5,
    release_year: 1998,
    icon_path: null,
    wallpaper_path: null,
    color: '#9370DB',
    rom_extensions: ['.gbc'],
  },
  {
    id: 'gba',
    name: 'Game Boy Advance',
    short_name: 'GBA',
    manufacturer: 'Nintendo',
    generation: 6,
    release_year: 2001,
    icon_path: null,
    wallpaper_path: null,
    color: '#4169E1',
    rom_extensions: ['.gba'],
  },
  {
    id: 'nds',
    name: 'Nintendo DS',
    short_name: 'NDS',
    manufacturer: 'Nintendo',
    generation: 7,
    release_year: 2004,
    icon_path: null,
    wallpaper_path: null,
    color: '#708090',
    rom_extensions: ['.nds', '.dsi'],
  },
  {
    id: '3ds',
    name: 'Nintendo 3DS',
    short_name: '3DS',
    manufacturer: 'Nintendo',
    generation: 8,
    release_year: 2011,
    icon_path: null,
    wallpaper_path: null,
    color: '#DC143C',
    rom_extensions: ['.3ds', '.cia', '.3dsx', '.app'],
  },
  // Sony
  {
    id: 'ps1',
    name: 'PlayStation',
    short_name: 'PS1',
    manufacturer: 'Sony',
    generation: 5,
    release_year: 1994,
    icon_path: null,
    wallpaper_path: null,
    color: '#003087',
    rom_extensions: ['.bin', '.cue', '.iso', '.img', '.pbp', '.chd'],
  },
  {
    id: 'ps2',
    name: 'PlayStation 2',
    short_name: 'PS2',
    manufacturer: 'Sony',
    generation: 6,
    release_year: 2000,
    icon_path: null,
    wallpaper_path: null,
    color: '#003087',
    rom_extensions: ['.iso', '.bin', '.chd', '.cso', '.gz'],
  },
  {
    id: 'psp',
    name: 'PlayStation Portable',
    short_name: 'PSP',
    manufacturer: 'Sony',
    generation: 7,
    release_year: 2004,
    icon_path: null,
    wallpaper_path: null,
    color: '#003087',
    rom_extensions: ['.iso', '.cso', '.pbp'],
  },
  {
    id: 'psvita',
    name: 'PlayStation Vita',
    short_name: 'Vita',
    manufacturer: 'Sony',
    generation: 8,
    release_year: 2011,
    icon_path: null,
    wallpaper_path: null,
    color: '#003087',
    rom_extensions: ['.vpk'],
  },
  // Sega
  {
    id: 'sms',
    name: 'Sega Master System',
    short_name: 'SMS',
    manufacturer: 'Sega',
    generation: 3,
    release_year: 1985,
    icon_path: null,
    wallpaper_path: null,
    color: '#0066CC',
    rom_extensions: ['.sms', '.sg'],
  },
  {
    id: 'genesis',
    name: 'Sega Genesis / Mega Drive',
    short_name: 'Genesis',
    manufacturer: 'Sega',
    generation: 4,
    release_year: 1988,
    icon_path: null,
    wallpaper_path: null,
    color: '#0066CC',
    rom_extensions: ['.md', '.smd', '.gen', '.bin'],
  },
  {
    id: 'saturn',
    name: 'Sega Saturn',
    short_name: 'Saturn',
    manufacturer: 'Sega',
    generation: 5,
    release_year: 1994,
    icon_path: null,
    wallpaper_path: null,
    color: '#2E8B57',
    rom_extensions: ['.iso', '.bin', '.cue', '.chd'],
  },
  {
    id: 'dreamcast',
    name: 'Sega Dreamcast',
    short_name: 'DC',
    manufacturer: 'Sega',
    generation: 6,
    release_year: 1998,
    icon_path: null,
    wallpaper_path: null,
    color: '#FF6600',
    rom_extensions: ['.gdi', '.cdi', '.chd'],
  },
  {
    id: 'gamegear',
    name: 'Sega Game Gear',
    short_name: 'GG',
    manufacturer: 'Sega',
    generation: 4,
    release_year: 1990,
    icon_path: null,
    wallpaper_path: null,
    color: '#1E90FF',
    rom_extensions: ['.gg'],
  },
  // Arcade
  {
    id: 'mame',
    name: 'MAME / Arcade',
    short_name: 'Arcade',
    manufacturer: null,
    generation: null,
    release_year: null,
    icon_path: null,
    wallpaper_path: null,
    color: '#FFD700',
    rom_extensions: ['.zip', '.7z'],
  },
  // Atari
  {
    id: 'atari2600',
    name: 'Atari 2600',
    short_name: '2600',
    manufacturer: 'Atari',
    generation: 2,
    release_year: 1977,
    icon_path: null,
    wallpaper_path: null,
    color: '#B22222',
    rom_extensions: ['.a26', '.bin'],
  },
  // SNK
  {
    id: 'neogeo',
    name: 'Neo Geo',
    short_name: 'Neo Geo',
    manufacturer: 'SNK',
    generation: 4,
    release_year: 1990,
    icon_path: null,
    wallpaper_path: null,
    color: '#DAA520',
    rom_extensions: ['.zip', '.7z'],
  },
  // NEC
  {
    id: 'pce',
    name: 'PC Engine / TurboGrafx-16',
    short_name: 'PCE',
    manufacturer: 'NEC',
    generation: 4,
    release_year: 1987,
    icon_path: null,
    wallpaper_path: null,
    color: '#CD5C5C',
    rom_extensions: ['.pce', '.cue', '.chd'],
  },
  // Microsoft
  {
    id: 'xbox',
    name: 'Xbox',
    short_name: 'Xbox',
    manufacturer: 'Microsoft',
    generation: 6,
    release_year: 2001,
    icon_path: null,
    wallpaper_path: null,
    color: '#107C10',
    rom_extensions: ['.iso', '.xiso'],
  },
  // PC / DOS
  {
    id: 'dos',
    name: 'DOS / PC',
    short_name: 'DOS',
    manufacturer: null,
    generation: null,
    release_year: null,
    icon_path: null,
    wallpaper_path: null,
    color: '#808080',
    rom_extensions: ['.exe', '.com', '.bat'],
  },
];

/**
 * Insert seed platforms into the platforms store when it is empty.
 * Called by FlatDb.open().
 */
export function loadPlatformSeeds(platforms: CollectionStore<PlatformRow>): void {
  if (platforms.count() > 0) return;

  const now = new Date();
  for (const seed of SEED_PLATFORMS) {
    platforms.insert({ ...seed, created_at: now, updated_at: now });
  }
}
