#!/usr/bin/env node
/**
 * generate-tokens.mjs
 *
 * Reads the design tokens defined in `libs/ui/src/themes/tokens.ts` and emits
 * two generated mirrors into `libs/ui/src/themes/__generated__/`:
 *
 *   - tokens.json : W3C DTCG (Design Tokens Community Group) format. A nested
 *                   tree grouped by export name where each leaf is
 *                   `{ "$value": <value>, "$type": <type> }`.
 *   - tokens.css  : `:root { --<group>-<key>: <value>; ... }` custom properties.
 *
 * The generator ONLY READS tokens.ts; it never modifies it.
 *
 * Token loading strategy:
 *   Primary  -> spawn a child Node process with `--experimental-strip-types`
 *               to import the TS module directly and serialize its exports.
 *   Fallback -> dependency-free regex extraction of the exported `as const`
 *               object literals (used only if strip-types is unavailable).
 *
 * Usage:
 *   node scripts/generate-tokens.mjs          # write the generated files
 *   node scripts/generate-tokens.mjs --check  # verify on-disk files are in sync
 *                                             # (exit 0 if synced, non-zero if drifted)
 *
 * Built-ins only. No external dependencies (repo is GPL-3.0).
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');

const TOKENS_TS = resolve(REPO_ROOT, 'libs/ui/src/themes/tokens.ts');
const OUT_DIR = resolve(REPO_ROOT, 'libs/ui/src/themes/__generated__');
const OUT_JSON = resolve(OUT_DIR, 'tokens.json');
const OUT_CSS = resolve(OUT_DIR, 'tokens.css');

const BANNER = 'DO NOT EDIT — generated by pnpm tokens:generate (source: libs/ui/src/themes/tokens.ts)';

/**
 * Token-group -> $type mapping for DTCG leaves.
 *   color        -> color hex strings (+ keyword strings like "transparent")
 *   spacing      -> dimension (px scale)
 *   fontSize     -> dimension (px)
 *   fontWeight   -> fontWeight
 *   lineHeight   -> number (unitless ratios)
 *   borderRadius -> dimension (px)
 *   shadow       -> shadow (composite object)
 *   duration     -> number (ms)
 *   zIndex       -> number (mixed numeric + "auto" keyword)
 *   breakpoint   -> dimension (px)
 *   gameCardSize -> dimension (px width/height pairs)
 *   widgetSize   -> number (grid col/row counts)
 *   iconSize     -> dimension (px)
 *
 * The map is keyed by the singular DTCG group name we publish under and points
 * at the matching export name in tokens.ts.
 */
const GROUP_META = {
  color: { source: 'colors', type: 'color', dimension: false },
  spacing: { source: 'spacing', type: 'dimension', dimension: true },
  fontSize: { source: 'fontSizes', type: 'dimension', dimension: true },
  fontWeight: { source: 'fontWeights', type: 'fontWeight', dimension: false },
  lineHeight: { source: 'lineHeights', type: 'number', dimension: false },
  borderRadius: { source: 'borderRadius', type: 'dimension', dimension: true },
  shadow: { source: 'shadows', type: 'shadow', dimension: false },
  duration: { source: 'durations', type: 'number', dimension: false },
  zIndex: { source: 'zIndex', type: 'number', dimension: false },
  breakpoint: { source: 'breakpoints', type: 'dimension', dimension: true },
  gameCardSize: { source: 'gameCardSizes', type: 'dimension', dimension: true },
  widgetSize: { source: 'widgetSizes', type: 'number', dimension: false },
  iconSize: { source: 'iconSizes', type: 'dimension', dimension: true },
};

/* --------------------------------------------------------------------------
 * Token loading
 * ------------------------------------------------------------------------ */

/**
 * Load token exports using Node's native TypeScript type-stripping by spawning
 * a child process that imports the TS module and serializes its exports.
 * @returns {{ ok: boolean, data?: object, error?: string }}
 */
function loadViaStripTypes() {
  const tokensUrl = new URL(`file://${TOKENS_TS}`).href;
  const script = `import * as t from ${JSON.stringify(tokensUrl)}; process.stdout.write(JSON.stringify(t));`;
  try {
    const out = execFileSync(
      process.execPath,
      ['--experimental-strip-types', '--input-type=module', '-e', script],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] },
    );
    return { ok: true, data: JSON.parse(out) };
  } catch (err) {
    return { ok: false, error: err && err.message ? err.message : String(err) };
  }
}

/**
 * Dependency-free fallback: extract each `export const <name> = { ... } as const;`
 * object literal from tokens.ts, strip line comments, then evaluate it via the
 * Function constructor (pure object literals only — no imports, no side effects).
 * @returns {object}
 */
function loadViaTextExtraction() {
  const src = readFileSync(TOKENS_TS, 'utf8');
  const result = {};
  // Match: export const NAME = <literal> as const;
  const re = /export\s+const\s+([A-Za-z0-9_]+)\s*=\s*([\s\S]*?)\s+as\s+const\s*;/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    const name = m[1];
    let body = m[2];
    // Remove line comments to keep the literal evaluable.
    body = body.replace(/\/\/[^\n]*$/gm, '');
    try {
      // eslint-disable-next-line no-new-func
      const value = Function(`"use strict"; return (${body});`)();
      result[name] = value;
    } catch (err) {
      throw new Error(`Failed to parse exported literal "${name}": ${err.message}`);
    }
  }
  if (Object.keys(result).length === 0) {
    throw new Error('Text extraction found no exported const literals in tokens.ts');
  }
  return result;
}

/**
 * Load tokens, preferring strip-types and falling back to text extraction.
 * @returns {{ tokens: object, path: 'strip-types' | 'text-extraction' }}
 */
function loadTokens() {
  const stripped = loadViaStripTypes();
  if (stripped.ok) {
    return { tokens: stripped.data, path: 'strip-types' };
  }
  process.stderr.write(
    `[generate-tokens] strip-types unavailable (${stripped.error}); falling back to text extraction\n`,
  );
  return { tokens: loadViaTextExtraction(), path: 'text-extraction' };
}

/* --------------------------------------------------------------------------
 * Helpers
 * ------------------------------------------------------------------------ */

/** Stable sort of object keys: numeric-looking keys numerically, then lexical. */
function sortKeys(keys) {
  return [...keys].sort((a, b) => {
    const an = Number(a);
    const bn = Number(b);
    const aNum = a !== '' && !Number.isNaN(an);
    const bNum = b !== '' && !Number.isNaN(bn);
    if (aNum && bNum) return an - bn;
    if (aNum) return -1;
    if (bNum) return 1;
    return a < b ? -1 : a > b ? 1 : 0;
  });
}

/** kebab-case a token key for use in a CSS custom property name. */
function kebab(key) {
  return String(key)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_.]+/g, '-')
    .replace(/-+/g, '-')
    .toLowerCase();
}

/** Format a dimension value as a px string (numbers only; pass through others). */
function asPx(value) {
  return typeof value === 'number' ? `${value}px` : String(value);
}

/* --------------------------------------------------------------------------
 * DTCG JSON generation
 * ------------------------------------------------------------------------ */

/**
 * Build a DTCG leaf for a primitive value within a group.
 * For dimension groups, numeric values are serialized as px strings.
 */
function dtcgLeaf(value, meta) {
  if (meta.dimension && typeof value === 'number') {
    return { $value: asPx(value), $type: 'dimension' };
  }
  return { $value: value, $type: meta.type };
}

/**
 * Convert a single token group value into a DTCG sub-tree.
 * Handles flat scalar maps, nested object values (gameCardSizes/widgetSizes),
 * and composite shadows.
 */
function dtcgGroup(groupValue, meta) {
  const node = {};
  for (const key of sortKeys(Object.keys(groupValue))) {
    const value = groupValue[key];
    if (meta.type === 'shadow') {
      // Composite shadow token: keep the structured value as-is under $value.
      node[key] = { $value: value, $type: 'shadow' };
    } else if (value !== null && typeof value === 'object') {
      // Nested dimension/number group (e.g. { width, height } or { cols, rows }).
      const inner = {};
      for (const innerKey of sortKeys(Object.keys(value))) {
        inner[innerKey] = dtcgLeaf(value[innerKey], meta);
      }
      node[key] = inner;
    } else {
      node[key] = dtcgLeaf(value, meta);
    }
  }
  return node;
}

/** Build the full DTCG JSON string from loaded tokens. */
function buildJson(tokens) {
  const root = { $description: BANNER };
  for (const groupName of Object.keys(GROUP_META)) {
    const meta = GROUP_META[groupName];
    const source = tokens[meta.source];
    if (source === undefined) continue;
    root[groupName] = dtcgGroup(source, meta);
  }
  return JSON.stringify(root, null, 2) + '\n';
}

/* --------------------------------------------------------------------------
 * CSS generation
 * ------------------------------------------------------------------------ */

/** Append CSS custom-property lines for one group into `lines`. */
function cssGroup(lines, groupName, groupValue, meta) {
  const prefix = kebab(groupName);
  for (const key of sortKeys(Object.keys(groupValue))) {
    const value = groupValue[key];
    if (meta.type === 'shadow') {
      // Emit a box-shadow string: offsetX offsetY blur color.
      const x = asPx(value.shadowOffset?.width ?? 0);
      const y = asPx(value.shadowOffset?.height ?? 0);
      const blur = asPx(value.shadowRadius ?? 0);
      const color = value.shadowColor ?? '#000';
      const opacity = value.shadowOpacity ?? 1;
      const shadow =
        color === 'transparent' || opacity === 0 ? 'none' : `${x} ${y} ${blur} ${color}`;
      lines.push(`  --${prefix}-${kebab(key)}: ${shadow};`);
    } else if (value !== null && typeof value === 'object') {
      for (const innerKey of sortKeys(Object.keys(value))) {
        const out = meta.dimension ? asPx(value[innerKey]) : String(value[innerKey]);
        lines.push(`  --${prefix}-${kebab(key)}-${kebab(innerKey)}: ${out};`);
      }
    } else {
      const out = meta.dimension ? asPx(value) : String(value);
      lines.push(`  --${prefix}-${kebab(key)}: ${out};`);
    }
  }
}

/** Build the full CSS string from loaded tokens. */
function buildCss(tokens) {
  const lines = [];
  for (const groupName of Object.keys(GROUP_META)) {
    const meta = GROUP_META[groupName];
    const source = tokens[meta.source];
    if (source === undefined) continue;
    cssGroup(lines, groupName, source, meta);
  }
  return `/* ${BANNER} */\n:root {\n${lines.join('\n')}\n}\n`;
}

/* --------------------------------------------------------------------------
 * Main
 * ------------------------------------------------------------------------ */

function main() {
  const checkMode = process.argv.includes('--check');

  const { tokens, path: loadPath } = loadTokens();
  const json = buildJson(tokens);
  const css = buildCss(tokens);

  if (checkMode) {
    const drifted = [];
    const compare = (file, expected) => {
      const actual = existsSync(file) ? readFileSync(file, 'utf8') : null;
      if (actual !== expected) drifted.push(file);
    };
    compare(OUT_JSON, json);
    compare(OUT_CSS, css);
    if (drifted.length > 0) {
      process.stderr.write(
        `[generate-tokens] Design tokens are out of sync. Drifted file(s):\n` +
          drifted.map((f) => `  - ${f}`).join('\n') +
          `\nRun 'pnpm tokens:generate' and commit the result.\n`,
      );
      process.exit(1);
    }
    process.stdout.write(`[generate-tokens] In sync (loader: ${loadPath}).\n`);
    return;
  }

  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_JSON, json);
  writeFileSync(OUT_CSS, css);
  process.stdout.write(
    `[generate-tokens] Wrote tokens.json and tokens.css (loader: ${loadPath}).\n`,
  );
}

main();
